/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_gui_q3_2024_blancaamaya;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;

public class Seleccion extends javax.swing.JFrame {

    DefaultTableModel mt = new DefaultTableModel();
    DefaultTableModel mt1 = new DefaultTableModel();
    DefaultTableModel mt2 = new DefaultTableModel();
    DefaultTableModel mt3 = new DefaultTableModel();
    DefaultTableModel mt4 = new DefaultTableModel();
    ArrayList<Estudiante> estudiantesGryffinder = new ArrayList<>();
    ArrayList<Estudiante> estudiantesHufflepuff = new ArrayList<>();
    ArrayList<Estudiante> estudiantesRavenClaw = new ArrayList<>();
    ArrayList<Estudiante> estudiantesSlytherin = new ArrayList<>();
    int contador1 = 0;
    int contador2 = 0;
    int contador3 = 0;
    int contador4 = 0;

    public Seleccion() {
        initComponents();
        String tabla[] = {"Nombre del estudiante", "Casa"};
        mt.setColumnIdentifiers(tabla);
        String tabla1[] = {"Nombre del estudiante", "Casa"};
        mt1.setColumnIdentifiers(tabla);
        String tabla2[] = {"Nombre del estudiante", "Casa"};
        mt2.setColumnIdentifiers(tabla);
        String tabla3[] = {"Nombre del estudiante", "Casa"};
        mt3.setColumnIdentifiers(tabla);
        String tabla4[] = {"Nombre del estudiante", "Casa"};
        mt4.setColumnIdentifiers(tabla);
        ListaSlytherin_JTable.setModel(mt1);
        ListaHufflePuff_JTable1.setModel(mt2);
        ListaRavenClaw_JTable1.setModel(mt3);
        ListaGryffinder_JTable1.setModel(mt4);
        ArrayList<String> array3 = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Input_JDialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        Texto_Alumno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Boton_Ok_InputDialog = new javax.swing.JButton();
        Boton_Cancelar_InputDialog = new javax.swing.JButton();
        Mensaje_JDialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Label_2 = new javax.swing.JLabel();
        Cerrar_Mensaje = new javax.swing.JButton();
        ListaEstudiantes_Slytherin = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaSlytherin_JTable = new javax.swing.JTable();
        TextoListas_Slytherin = new javax.swing.JLabel();
        Eliminar_Slytherin = new javax.swing.JButton();
        Salir_Slytherin = new javax.swing.JButton();
        TextoEliminar_Slytherin = new javax.swing.JLabel();
        ListaEstudiantes_HufflePuff = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaHufflePuff_JTable1 = new javax.swing.JTable();
        TextoListas_HufflePuff = new javax.swing.JLabel();
        Eliminar_HufflePuff = new javax.swing.JButton();
        Salir_HufflePuff = new javax.swing.JButton();
        TextoEliminar_HufflePuff = new javax.swing.JLabel();
        ListaEstudiantes_RavenClaw = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaRavenClaw_JTable1 = new javax.swing.JTable();
        TextoListas_RavenClaw = new javax.swing.JLabel();
        Eliminar_RavenClaw = new javax.swing.JButton();
        Salir_RavenClaw = new javax.swing.JButton();
        TextoEliminar_Slytherin2 = new javax.swing.JLabel();
        ListaEstudiantes_Gryffinder = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListaGryffinder_JTable1 = new javax.swing.JTable();
        TextoListas_Gryffinder = new javax.swing.JLabel();
        Eliminar_Gryffinder = new javax.swing.JButton();
        Salir_Gryffinder = new javax.swing.JButton();
        TextoEliminar_Gryffinder = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Boton_Sombrero = new javax.swing.JButton();
        Boton_Slytherin = new javax.swing.JButton();
        TextField_Verde = new javax.swing.JTextField();
        Boton_Hufflepuff = new javax.swing.JButton();
        TextField_Amarillo = new javax.swing.JTextField();
        Boton_Gryffinder = new javax.swing.JButton();
        TextField_Rojo1 = new javax.swing.JTextField();
        Boton_RavenClaw = new javax.swing.JButton();
        TextField_Azul1 = new javax.swing.JTextField();
        TocaSombrerotexto = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        Texto_Alumno.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Texto_Alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Texto_AlumnoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Escriba el nombre del alumno ");

        Boton_Ok_InputDialog.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Boton_Ok_InputDialog.setText("Ok");
        Boton_Ok_InputDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_Ok_InputDialogMouseClicked(evt);
            }
        });
        Boton_Ok_InputDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Ok_InputDialogActionPerformed(evt);
            }
        });

        Boton_Cancelar_InputDialog.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Boton_Cancelar_InputDialog.setText("Salir");
        Boton_Cancelar_InputDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_Cancelar_InputDialogMouseClicked(evt);
            }
        });
        Boton_Cancelar_InputDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Cancelar_InputDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(Boton_Ok_InputDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Boton_Cancelar_InputDialog))
                        .addComponent(Texto_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Texto_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_Ok_InputDialog)
                    .addComponent(Boton_Cancelar_InputDialog))
                .addContainerGap())
        );

        javax.swing.GroupLayout Input_JDialogLayout = new javax.swing.GroupLayout(Input_JDialog.getContentPane());
        Input_JDialog.getContentPane().setLayout(Input_JDialogLayout);
        Input_JDialogLayout.setHorizontalGroup(
            Input_JDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Input_JDialogLayout.setVerticalGroup(
            Input_JDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("La casa seleccionada ha sido");

        Label_2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        Cerrar_Mensaje.setText("Cerrar");
        Cerrar_Mensaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cerrar_MensajeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(Label_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cerrar_Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Cerrar_Mensaje)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout Mensaje_JDialogLayout = new javax.swing.GroupLayout(Mensaje_JDialog.getContentPane());
        Mensaje_JDialog.getContentPane().setLayout(Mensaje_JDialogLayout);
        Mensaje_JDialogLayout.setHorizontalGroup(
            Mensaje_JDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Mensaje_JDialogLayout.setVerticalGroup(
            Mensaje_JDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ListaSlytherin_JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre del estudiante", "Casa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ListaSlytherin_JTable);

        TextoListas_Slytherin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TextoListas_Slytherin.setText("Listas de estudiantes de Slytherin");

        Eliminar_Slytherin.setText("Eliminar");
        Eliminar_Slytherin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar_SlytherinMouseClicked(evt);
            }
        });
        Eliminar_Slytherin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_SlytherinActionPerformed(evt);
            }
        });

        Salir_Slytherin.setText("Salir");
        Salir_Slytherin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Salir_SlytherinMouseClicked(evt);
            }
        });

        TextoEliminar_Slytherin.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextoEliminar_Slytherin.setText("Selecciona de la tabla el estudiante que desea eliminar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Eliminar_Slytherin, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Salir_Slytherin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(TextoListas_Slytherin)
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TextoEliminar_Slytherin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(TextoListas_Slytherin, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(TextoEliminar_Slytherin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eliminar_Slytherin)
                    .addComponent(Salir_Slytherin))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout ListaEstudiantes_SlytherinLayout = new javax.swing.GroupLayout(ListaEstudiantes_Slytherin.getContentPane());
        ListaEstudiantes_Slytherin.getContentPane().setLayout(ListaEstudiantes_SlytherinLayout);
        ListaEstudiantes_SlytherinLayout.setHorizontalGroup(
            ListaEstudiantes_SlytherinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ListaEstudiantes_SlytherinLayout.setVerticalGroup(
            ListaEstudiantes_SlytherinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ListaHufflePuff_JTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre del estudiante", "Casa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ListaHufflePuff_JTable1);

        TextoListas_HufflePuff.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TextoListas_HufflePuff.setText("Listas de estudiantes de HufflePuff");

        Eliminar_HufflePuff.setText("Eliminar");
        Eliminar_HufflePuff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar_HufflePuffMouseClicked(evt);
            }
        });
        Eliminar_HufflePuff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_HufflePuffActionPerformed(evt);
            }
        });

        Salir_HufflePuff.setText("Salir");
        Salir_HufflePuff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Salir_HufflePuffMouseClicked(evt);
            }
        });

        TextoEliminar_HufflePuff.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextoEliminar_HufflePuff.setText("Selecciona de la tabla el estudiante que desea eliminar");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Eliminar_HufflePuff, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Salir_HufflePuff, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(TextoListas_HufflePuff)
                        .addGap(0, 60, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TextoEliminar_HufflePuff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(TextoListas_HufflePuff, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(TextoEliminar_HufflePuff, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eliminar_HufflePuff)
                    .addComponent(Salir_HufflePuff))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout ListaEstudiantes_HufflePuffLayout = new javax.swing.GroupLayout(ListaEstudiantes_HufflePuff.getContentPane());
        ListaEstudiantes_HufflePuff.getContentPane().setLayout(ListaEstudiantes_HufflePuffLayout);
        ListaEstudiantes_HufflePuffLayout.setHorizontalGroup(
            ListaEstudiantes_HufflePuffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ListaEstudiantes_HufflePuffLayout.setVerticalGroup(
            ListaEstudiantes_HufflePuffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ListaRavenClaw_JTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre del estudiante", "Casa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(ListaRavenClaw_JTable1);

        TextoListas_RavenClaw.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TextoListas_RavenClaw.setText("Listas de estudiantes de RavenClaw");

        Eliminar_RavenClaw.setText("Eliminar");
        Eliminar_RavenClaw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar_RavenClawMouseClicked(evt);
            }
        });
        Eliminar_RavenClaw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_RavenClawActionPerformed(evt);
            }
        });

        Salir_RavenClaw.setText("Salir");
        Salir_RavenClaw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Salir_RavenClawMouseClicked(evt);
            }
        });

        TextoEliminar_Slytherin2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextoEliminar_Slytherin2.setText("Selecciona de la tabla el estudiante que desea eliminar");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Eliminar_RavenClaw, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Salir_RavenClaw, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(TextoListas_RavenClaw)
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TextoEliminar_Slytherin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(TextoListas_RavenClaw, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(TextoEliminar_Slytherin2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eliminar_RavenClaw)
                    .addComponent(Salir_RavenClaw))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout ListaEstudiantes_RavenClawLayout = new javax.swing.GroupLayout(ListaEstudiantes_RavenClaw.getContentPane());
        ListaEstudiantes_RavenClaw.getContentPane().setLayout(ListaEstudiantes_RavenClawLayout);
        ListaEstudiantes_RavenClawLayout.setHorizontalGroup(
            ListaEstudiantes_RavenClawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ListaEstudiantes_RavenClawLayout.setVerticalGroup(
            ListaEstudiantes_RavenClawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ListaGryffinder_JTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre del estudiante", "Casa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(ListaGryffinder_JTable1);

        TextoListas_Gryffinder.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TextoListas_Gryffinder.setText("Listas de estudiantes de Gryffinder");

        Eliminar_Gryffinder.setText("Eliminar");
        Eliminar_Gryffinder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar_GryffinderMouseClicked(evt);
            }
        });
        Eliminar_Gryffinder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_GryffinderActionPerformed(evt);
            }
        });

        Salir_Gryffinder.setText("Salir");
        Salir_Gryffinder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Salir_GryffinderMouseClicked(evt);
            }
        });
        Salir_Gryffinder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir_GryffinderActionPerformed(evt);
            }
        });

        TextoEliminar_Gryffinder.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextoEliminar_Gryffinder.setText("Selecciona de la tabla el estudiante que desea eliminar");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Eliminar_Gryffinder, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Salir_Gryffinder, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(TextoListas_Gryffinder)
                        .addGap(0, 60, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TextoEliminar_Gryffinder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(TextoListas_Gryffinder, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(TextoEliminar_Gryffinder, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eliminar_Gryffinder)
                    .addComponent(Salir_Gryffinder))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout ListaEstudiantes_GryffinderLayout = new javax.swing.GroupLayout(ListaEstudiantes_Gryffinder.getContentPane());
        ListaEstudiantes_Gryffinder.getContentPane().setLayout(ListaEstudiantes_GryffinderLayout);
        ListaEstudiantes_GryffinderLayout.setHorizontalGroup(
            ListaEstudiantes_GryffinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ListaEstudiantes_GryffinderLayout.setVerticalGroup(
            ListaEstudiantes_GryffinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_Sombrero.setBackground(new java.awt.Color(0, 0, 0, 0));
        Boton_Sombrero.setForeground(new java.awt.Color(51, 51, 51));
        Boton_Sombrero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/sombrero.png"))); // NOI18N
        Boton_Sombrero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_SombreroMouseClicked(evt);
            }
        });
        Boton_Sombrero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SombreroActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Sombrero, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 210, 200));

        Boton_Slytherin.setBackground(new java.awt.Color(0, 0, 0, 0));
        Boton_Slytherin.setForeground(new java.awt.Color(51, 51, 55));
        Boton_Slytherin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/slytherin.png"))); // NOI18N
        Boton_Slytherin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_SlytherinMouseClicked(evt);
            }
        });
        Boton_Slytherin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SlytherinActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Slytherin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 130, 110));

        TextField_Verde.setBackground(new java.awt.Color(0, 102, 51));
        TextField_Verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_VerdeActionPerformed(evt);
            }
        });
        jPanel1.add(TextField_Verde, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 100, 40));

        Boton_Hufflepuff.setBackground(new java.awt.Color(0, 0, 0, 0));
        Boton_Hufflepuff.setForeground(new java.awt.Color(51, 51, 55));
        Boton_Hufflepuff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/hufflepuff.png"))); // NOI18N
        Boton_Hufflepuff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_HufflepuffMouseClicked(evt);
            }
        });
        Boton_Hufflepuff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_HufflepuffActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Hufflepuff, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        TextField_Amarillo.setBackground(new java.awt.Color(255, 255, 0));
        TextField_Amarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_AmarilloActionPerformed(evt);
            }
        });
        jPanel1.add(TextField_Amarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 100, 30));

        Boton_Gryffinder.setBackground(new java.awt.Color(0, 0, 0, 0));
        Boton_Gryffinder.setForeground(new java.awt.Color(51, 51, 51));
        Boton_Gryffinder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/gryffindor.png"))); // NOI18N
        Boton_Gryffinder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_GryffinderMouseClicked(evt);
            }
        });
        Boton_Gryffinder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_GryffinderActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Gryffinder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        TextField_Rojo1.setBackground(new java.awt.Color(153, 0, 0));
        TextField_Rojo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Rojo1ActionPerformed(evt);
            }
        });
        jPanel1.add(TextField_Rojo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, 30));

        Boton_RavenClaw.setBackground(new java.awt.Color(0, 0, 0, 0));
        Boton_RavenClaw.setForeground(new java.awt.Color(51, 51, 55));
        Boton_RavenClaw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ravenclaw.png"))); // NOI18N
        Boton_RavenClaw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_RavenClawMouseClicked(evt);
            }
        });
        jPanel1.add(Boton_RavenClaw, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 120, -1));

        TextField_Azul1.setBackground(new java.awt.Color(0, 51, 204));
        TextField_Azul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Azul1ActionPerformed(evt);
            }
        });
        jPanel1.add(TextField_Azul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 90, 40));

        TocaSombrerotexto.setBackground(new java.awt.Color(0, 0, 0));
        TocaSombrerotexto.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        TocaSombrerotexto.setForeground(new java.awt.Color(255, 255, 255));
        TocaSombrerotexto.setText("Toca el sombrero seleccionador ");
        jPanel1.add(TocaSombrerotexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 190, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/CEREMONIA DE SELECCIón.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_VerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_VerdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_VerdeActionPerformed

    private void TextField_AmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_AmarilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_AmarilloActionPerformed

    private void TextField_Azul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Azul1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Azul1ActionPerformed

    private void Boton_SombreroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SombreroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_SombreroActionPerformed

    private void Boton_SombreroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_SombreroMouseClicked
        this.setVisible(false);
        expandir(Input_JDialog);
    }//GEN-LAST:event_Boton_SombreroMouseClicked

    private void Boton_GryffinderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_GryffinderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_GryffinderActionPerformed

    private void Boton_HufflepuffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_HufflepuffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_HufflepuffActionPerformed

    private void Boton_SlytherinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SlytherinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_SlytherinActionPerformed

    private void Boton_GryffinderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_GryffinderMouseClicked

        this.setVisible(false);
        expandir(ListaEstudiantes_Gryffinder);
    }//GEN-LAST:event_Boton_GryffinderMouseClicked

    private void Boton_HufflepuffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_HufflepuffMouseClicked

        this.setVisible(false);
        expandir(ListaEstudiantes_HufflePuff);
    }//GEN-LAST:event_Boton_HufflepuffMouseClicked

    private void Boton_RavenClawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_RavenClawMouseClicked

        this.setVisible(false);
        expandir(ListaEstudiantes_RavenClaw);
    }//GEN-LAST:event_Boton_RavenClawMouseClicked

    private void Boton_SlytherinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_SlytherinMouseClicked

        this.setVisible(false);
        expandir(ListaEstudiantes_Slytherin);
    }//GEN-LAST:event_Boton_SlytherinMouseClicked

    private void Texto_AlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Texto_AlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Texto_AlumnoActionPerformed

    private void Boton_Ok_InputDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Ok_InputDialogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Ok_InputDialogActionPerformed

    private void Boton_Ok_InputDialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_Ok_InputDialogMouseClicked

        String nombre = Texto_Alumno.getText();
        Random random = new Random();
        String casa = "";
        int casaAlt = random.nextInt(4);
        switch (casaAlt) {
            case 0 -> {
                casa = "Slytherin";
                estudiantesSlytherin.add(new Estudiante(nombre, casa));
                contador4++;
                mt1.addRow(new Object[]{nombre, casa});
                break;
            }
            case 1 -> {
                casa = "Gryffinder";
                estudiantesGryffinder.add(new Estudiante(nombre, casa));
                contador1++;
                mt4.addRow(new Object[]{nombre, casa});
                break;
            }
            case 2 -> {
                casa = "Hufflepuff";
                estudiantesHufflepuff.add(new Estudiante(nombre, casa));
                contador2++;
                mt2.addRow(new Object[]{nombre, casa});
                break;
            }
            case 3 -> {
                casa = "RavenClaw";
                estudiantesRavenClaw.add(new Estudiante(nombre, casa));
                contador3++;
                mt3.addRow(new Object[]{nombre, casa});
                break;
            }
        }

        mt.addRow(new Object[]{nombre, casa});
        Texto_Alumno.setText("");

        Input_JDialog.dispose();
        this.setVisible(true);
        if (mt1.getRowCount() > 0 || mt2.getRowCount() > 0 || mt3.getRowCount() > 0 || mt4.getRowCount() > 0) {
            String casaAsignada = "";
            if (mt1.getRowCount() > 0) {
                int finFila = mt1.getRowCount() - 1;
                casaAsignada = mt1.getValueAt(finFila, 1).toString();
            } else if (mt2.getRowCount() > 0) {
                int finFila = mt2.getRowCount() - 1;
                casaAsignada = mt2.getValueAt(finFila, 1).toString();
            } else if (mt3.getRowCount() > 0) {
                int finFila = mt3.getRowCount() - 1;
                casaAsignada = mt3.getValueAt(finFila, 1).toString();
            } else if (mt4.getRowCount() > 0) {
                int finFila = mt4.getRowCount() - 1;
                casaAsignada = mt4.getValueAt(finFila, 1).toString();
            }
            Label_2.setText(casaAsignada);
            this.setVisible(false);
            expandir(Mensaje_JDialog);
        } else {
            Label_2.setText("No hay registro de estudiantes.");
        }
        actualizarContadores();
    }//GEN-LAST:event_Boton_Ok_InputDialogMouseClicked

    private void Boton_Cancelar_InputDialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_Cancelar_InputDialogMouseClicked
        Texto_Alumno.setText("");
        Input_JDialog.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_Boton_Cancelar_InputDialogMouseClicked

    private void Eliminar_SlytherinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_SlytherinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Eliminar_SlytherinActionPerformed

    private void Eliminar_HufflePuffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_HufflePuffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Eliminar_HufflePuffActionPerformed

    private void Eliminar_RavenClawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_RavenClawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Eliminar_RavenClawActionPerformed

    private void Eliminar_GryffinderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_GryffinderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Eliminar_GryffinderActionPerformed

    private void Boton_Cancelar_InputDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Cancelar_InputDialogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Cancelar_InputDialogActionPerformed

    private void Salir_HufflePuffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir_HufflePuffMouseClicked

        ListaEstudiantes_HufflePuff.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_Salir_HufflePuffMouseClicked

    private void Salir_RavenClawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir_RavenClawMouseClicked

        ListaEstudiantes_RavenClaw.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_Salir_RavenClawMouseClicked

    private void Salir_GryffinderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir_GryffinderMouseClicked

        ListaEstudiantes_Gryffinder.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_Salir_GryffinderMouseClicked

    private void Salir_GryffinderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir_GryffinderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Salir_GryffinderActionPerformed

    private void Cerrar_MensajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cerrar_MensajeMouseClicked
        Mensaje_JDialog.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_Cerrar_MensajeMouseClicked

    private void Salir_SlytherinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir_SlytherinMouseClicked

        ListaEstudiantes_Slytherin.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_Salir_SlytherinMouseClicked

    private void Eliminar_SlytherinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_SlytherinMouseClicked
        int selecionFila2 = ListaSlytherin_JTable.getSelectedRow();
        if (selecionFila2 != -1) {
            mt.removeRow(selecionFila2);
            if (selecionFila2 < estudiantesSlytherin.size()) {
                estudiantesSlytherin.remove(selecionFila2);
                contador4--;
            }
            actualizarContadores();
        } else {

        }
    }//GEN-LAST:event_Eliminar_SlytherinMouseClicked

    private void Eliminar_HufflePuffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_HufflePuffMouseClicked
        int selecionFila3 = ListaHufflePuff_JTable1.getSelectedRow();
        if (selecionFila3 != -1) {
            mt2.removeRow(selecionFila3);
            if (selecionFila3 < estudiantesHufflepuff.size()) {
                estudiantesHufflepuff.remove(selecionFila3);
                contador2--;
            }
            actualizarContadores();
        } else {

        }
    }//GEN-LAST:event_Eliminar_HufflePuffMouseClicked

    private void Eliminar_RavenClawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_RavenClawMouseClicked
        int selecionFila4 = ListaRavenClaw_JTable1.getSelectedRow();
        if (selecionFila4 != -1) {
            mt3.removeRow(selecionFila4);
            if (selecionFila4 < estudiantesRavenClaw.size()) {
                estudiantesRavenClaw.remove(selecionFila4);
                contador3--;
            }
            actualizarContadores();
        } else {

        }
    }//GEN-LAST:event_Eliminar_RavenClawMouseClicked

    private void Eliminar_GryffinderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_GryffinderMouseClicked
        int selecionFila5 = ListaGryffinder_JTable1.getSelectedRow();
        if (selecionFila5 != -1) {
            mt4.removeRow(selecionFila5);
            if (selecionFila5 < estudiantesGryffinder.size()) {
                estudiantesGryffinder.remove(selecionFila5);
                contador1--;
            }
            actualizarContadores();
        } else {

        }
    }//GEN-LAST:event_Eliminar_GryffinderMouseClicked

    private void TextField_Rojo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Rojo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Rojo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seleccion().setVisible(true);
            }
        });
    }

    public void expandir(JDialog x) {
        x.pack();
        x.setLocationRelativeTo(this);
        x.setModal(true);
        x.setVisible(true);
    }

    private void actualizarContadores() {
        TextField_Rojo1.setText(String.valueOf(contador1));
        TextField_Amarillo.setText(String.valueOf(contador2));
        TextField_Azul1.setText(String.valueOf(contador3));
        TextField_Verde.setText(String.valueOf(contador4));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Cancelar_InputDialog;
    private javax.swing.JButton Boton_Gryffinder;
    private javax.swing.JButton Boton_Hufflepuff;
    private javax.swing.JButton Boton_Ok_InputDialog;
    private javax.swing.JButton Boton_RavenClaw;
    private javax.swing.JButton Boton_Slytherin;
    private javax.swing.JButton Boton_Sombrero;
    private javax.swing.JButton Cerrar_Mensaje;
    private javax.swing.JButton Eliminar_Gryffinder;
    private javax.swing.JButton Eliminar_HufflePuff;
    private javax.swing.JButton Eliminar_RavenClaw;
    private javax.swing.JButton Eliminar_Slytherin;
    private javax.swing.JLabel Fondo;
    private javax.swing.JDialog Input_JDialog;
    private javax.swing.JLabel Label_2;
    private javax.swing.JDialog ListaEstudiantes_Gryffinder;
    private javax.swing.JDialog ListaEstudiantes_HufflePuff;
    private javax.swing.JDialog ListaEstudiantes_RavenClaw;
    private javax.swing.JDialog ListaEstudiantes_Slytherin;
    private javax.swing.JTable ListaGryffinder_JTable1;
    private javax.swing.JTable ListaHufflePuff_JTable1;
    private javax.swing.JTable ListaRavenClaw_JTable1;
    private javax.swing.JTable ListaSlytherin_JTable;
    private javax.swing.JDialog Mensaje_JDialog;
    private javax.swing.JButton Salir_Gryffinder;
    private javax.swing.JButton Salir_HufflePuff;
    private javax.swing.JButton Salir_RavenClaw;
    private javax.swing.JButton Salir_Slytherin;
    private javax.swing.JTextField TextField_Amarillo;
    private javax.swing.JTextField TextField_Azul1;
    private javax.swing.JTextField TextField_Rojo1;
    private javax.swing.JTextField TextField_Verde;
    private javax.swing.JLabel TextoEliminar_Gryffinder;
    private javax.swing.JLabel TextoEliminar_HufflePuff;
    private javax.swing.JLabel TextoEliminar_Slytherin;
    private javax.swing.JLabel TextoEliminar_Slytherin2;
    private javax.swing.JLabel TextoListas_Gryffinder;
    private javax.swing.JLabel TextoListas_HufflePuff;
    private javax.swing.JLabel TextoListas_RavenClaw;
    private javax.swing.JLabel TextoListas_Slytherin;
    private javax.swing.JTextField Texto_Alumno;
    private javax.swing.JLabel TocaSombrerotexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
